name: Build and Upload Go Website Binary

on:
  push:
    branches:
      - live

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go environment
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Build Go binary
      env:
        SPT_CLIENT_ID: ${{ secrets.SPT_CLIENT_ID }}
        SPT_CLIENT_SECRET: ${{ secrets.SPT_CLIENT_SECRET }}
        SPT_REFRESH_TOKEN: ${{ secrets.SPT_REFRESH_TOKEN }}
        SPT_TOKEN_EXPIRY: ${{ secrets.SPT_TOKEN_EXPIRY }}
        SPT_ACCESS_TOKEN: ${{ secrets.SPT_ACCESS_TOKEN }}
      run: go build 

    - name: Upload wesbsite binary via SSH
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: personal_website
        target: /home/limpingm/tmp/

    - name: ssh to server and redeploy site
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: bash ~/scripts/deploy_website.sh
