name: Build and Upload Go Binary

on:
  push:
    branches:
      - live

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go environment
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Build Go binary
      run: go build 

    - name: Upload binary via SSH
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: personal_website
        target: /tmp/

    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          kill $(lsof -t -i:${{ secrets.WEB_PORT }}) 
          chmod +x /tmp/personal_website
          sudo rm -f /usr/bin/personal_website
          sudo mv /tmp/personal_website /usr/bin
          nohup personal_website > /dev/null 2>&1 &
